server:
  port: 8080
spring:
  application:
    name: BookStoreBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstoredb
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update  # Automatically create or update tables
    show-sql: true  # Print SQL statements in the logs
